esphome:
  name: esphome-pico
  friendly_name: esphome-pico

rp2040:
  board: rpipicow
  framework:
    # Required until https://github.com/platformio/platform-raspberrypi/pull/36 is merged
    platform_version: https://github.com/maxgerhardt/platform-raspberrypi.git

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "6kZ1QIP7aNf37UG1AgqP7VEHXb8EwAAnPPdVqvZQtgA="

ota:
  password: "681b9016980c121ffba4494b07cdd0d4"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.0.102
    gateway: 192.168.0.1
    subnet: 255.255.255.0

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "Esphome-Pico Fallback Hotspot"
    password: "p657vmYaw0CX"
binary_sensor:
  - platform: status
    name: "PicoLight"
  
switch:
  - platform: gpio
    pin: GPIO0
    inverted: True
    name: "picolight"
    id: picolight 
  - platform: gpio
    pin: GPIO1
    inverted: True
    name: "picolight1"
    id: picolight1       